# Set theme
theme: garth-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate

# Site settings
url: 'https://comicsclub.netlify.com/'
baseurl: ''
title: 'Comics Club'
description: 'The Official Comics Club Blog'
permalink: pretty
logo: "images/logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "There isn't much going on here yet, but watch this space"
